# Generated by Django 2.1.5 on 2019-04-14 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('post_id', models.CharField(max_length=200)),
                ('comment_time', models.DateTimeField(default=None)),
                ('username', models.CharField(default=None, max_length=200)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=20)),
                ('release_time', models.CharField(blank=True, max_length=50)),
                ('ratings_number', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=200)),
                ('star', models.CharField(max_length=200)),
                ('movie_length', models.CharField(max_length=30)),
                ('movie_type', models.CharField(max_length=200)),
                ('storyline', models.CharField(max_length=400)),
                ('trailer_embed_link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='MovieFans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.FileField(blank=True, upload_to='')),
                ('favorite', models.CharField(max_length=400)),
                ('recommand_movie_list', models.CharField(max_length=400)),
                ('rating_history', models.CharField(max_length=4000)),
                ('shopping_history', models.CharField(max_length=400)),
                ('comment', models.ManyToManyField(to='movie_processor.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('post_time', models.DateTimeField()),
                ('username', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=1)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_processor.Movie')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_picture', models.FileField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='moviefans',
            name='post',
            field=models.ManyToManyField(to='movie_processor.Post'),
        ),
        migrations.AddField(
            model_name='moviefans',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moviefans',
            name='watching_histpry',
            field=models.ManyToManyField(to='movie_processor.Movie'),
        ),
    ]
