# Generated by Django 2.1.5 on 2019-04-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_processor', '0003_auto_20190415_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefans',
            name='content_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
